### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by EnderVod** [Wolferos/Hearts-of-Iron-IV-The-Great-War#106]
I need to know when you will update the mod, I know a lot of people who love the mod and wanted to know when the new update will come out, a lot of people think mod has died, you need to launch a new update soon, there is already a lot that I And the other members did, so I think it's already good for a next update, please do it for the community, the mod has a lot of fans not only in Brazil but worldwide

**Comment by Wolferos** [comment]
Next update this week or next week with the new Patch 1.4.2
