### ISSUE TITLE
New advisors, companies and generals for France

### ISSUE THREAD

**Issue by ghost** [Wolferos/Hearts-of-Iron-IV-The-Great-War#110]
Hello,
I've been following your mod for some time now. I must say thank you for your hard work and wonderful job! It's a delightful mod!

I would like to help you regarding France's advisors, generals and companies. Also, I'm not great with programming and coding, I just want to share with you my researches.

I hope it's not the wrong place to post. Here's my proposal to enhance France in the game (don't mind the effects):
https://we.tl/LH5P3onpvX

And I understood you speak French... 
Cheers

------------------

Bonjour,
Je suis avec intérêt votre mod depuis quelques temps maintenant. Je tenais à vous remercier pour votre superbe travail ! Ce mod est une merveille !

Je souhaiterais vous aider en ce qui concerne la France et ses conseillers, industries et généraux... Je ne suis pas très doué en programmation et codage, c'est plus dans l'intention de partager avec vous mes recherches sur le sujet.

En espérant ne pas mettre trompé d'endroit pour poster. Veuillez trouver ci-dessous mes idées et recherches pour étoffer la France dans votre mod (ne pas faire attention aux effets proposés):
https://we.tl/LH5P3onpvX

**Comment by DevilIris** [comment]
mm happen to the files?
