### ISSUE TITLE
There are no GFX_hoi4tgw_navalcanons

### ISSUE THREAD

**Issue by skullbe** [Wolferos/Hearts-of-Iron-IV-The-Great-War#128]
there are no icon 'GFX_hoi4tgw_navalcanons' so NF naval focus icon have problem.

you should add it or replace another icon

**Comment by Wolferos** [comment]
The icon is located here [gfx/interface/goals/hoi4tgw](https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/tree/develop/mod/thegreatwar/gfx/interface/goals/hoi4tgw) and declared as follow in 
[interface/goals.gfx](https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/blob/develop/mod/thegreatwar/interface/goals.gfx)

> SpriteType = {
	name = "GFX_hoi4tgw_navalcanons"
	texturefile = "gfx/interface/goals/hoi4tgw/ww1_nationalfocus_asiarus.dds"
}

What's the problem?

**Comment by skullbe** [comment]
In NF, that parts are missing. '?' icon appeared

**Comment by MasterWaifuman** [comment]
The thing is that this icon missing only in GER and AUH focus trees. I looked through and all is ok. But icons are missing. In fact, i don't know what is wrong and log doesn't say anything but if you want this icon so much just type in console "reload focus" it works.
