### ISSUE TITLE
Update log

### ISSUE THREAD

**Issue by MasterWaifuman** [Wolferos/Hearts-of-Iron-IV-The-Great-War#138]
Why didn't you add me as a contributor in "THE FOLLOWING PEOPLE ALSO CONTRIBUTED ON THE PROJECT" section?

**Comment by DevilIris** [comment]
He is going to update relax waifuman xD

BTW all the names.who help are here:

@MasterWaifuman // Making the sov focus tree and fixing a lot of things
MurderMountain//Fixing Mexico Focus tree 

This name should be added to the credits too. 

Common Waifuman made a lot of stuff or the most of the work. xD

_Sent from my Samsung SM-G532M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MasterWaifuman** [comment]
ok, i guess

**Comment by DevilIris** [comment]
You should leave it open this issue. So he can see it and update the log. 

_Sent from my Samsung SM-G532M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MasterWaifuman** [comment]
Also "Neutral Ideology can now send volunteers with 10% World Tension" should be "Neutral Ideology can now send volunteers with 15% World Tension"

**Comment by DevilIris** [comment]
Agree. With that.

_Sent from my Samsung SM-G532M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MasterWaifuman** [comment]
And also maybe add "Fixed some interface errors"

**Comment by MasterWaifuman** [comment]
(from my last pull request)

**Comment by DevilIris** [comment]
I didnt watch that push. What kind of interface errors?

_Sent from my Samsung SM-G532M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MasterWaifuman** [comment]
https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/pull/137/commits/905f244d66570b4380863de1b02deb55a67356b6

**Comment by MasterWaifuman** [comment]
and this https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/pull/137/commits/b5a93811eb00f93634f8e7da460801fcaa3e4888

**Comment by MasterWaifuman** [comment]
and this too https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/pull/137/commits/ff85fab09d9508c06115104b3619fb7767a8e11b

**Comment by MasterWaifuman** [comment]
I also fixed some of events: https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/pull/137/commits/b98601ad661b4b95a9f97d35931de6c33ec9847b and https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/pull/137/commits/7863cd4a43a651aa0f2715c7924b98b522e2179d

**Comment by DevilIris** [comment]
Ohh yep you fixed. I didnt watch that push. I edit my first comment in this issue thread. Maybe he forget to paste the name( that happens to me a lot). 

_Sent from my Samsung SM-G532M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MasterWaifuman** [comment]
Full request if want: https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/pull/137

**Comment by DevilIris** [comment]
Is all ready merge. Things that we needs to fix are the impassible areas from 1.31. That we need them so badly. In the 1.42 paradox fix the areas 

_Sent from my Samsung SM-G532M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Wolferos** [comment]
Updated,

Don't worry, we have never forgotten a contributor in the past, it was a small commit mistake wich is fixed now.

**Comment by MasterWaifuman** [comment]
Thanks. And issue is closed i suppose
