### ISSUE TITLE
Historical mode

### ISSUE THREAD

**Issue by MoffKadir** [Wolferos/Hearts-of-Iron-IV-The-Great-War#147]
does historical mode work in this mod? if they work, please fix belgium, they going into the branch "conquer benelux"  IRT they was a friends with Antanta, IMHO and don't conquer Netherlands

**Comment by MasterWaifuman** [comment]
You sure you turned on historical mode? In my test games belgium never went lower than benilux focus and never conquered it.

**Comment by MoffKadir** [comment]
yes. 
in my game begin First World War, and Belgium annex the Netherlands

**Comment by MoffKadir** [comment]
sorry my english, it's weak, i know

**Comment by MoffKadir** [comment]
v 0.4.2 from moddb

**Comment by MasterWaifuman** [comment]
In ai_chance is modifier that sets factor to 0 if historical on, so i don't know whats wrong. I will test it tomorrow again and see what happens.

**Comment by MoffKadir** [comment]
ok

**Comment by MoffKadir** [comment]
where i can see the order of taking focuses in the historical mode?

**Comment by MoffKadir** [comment]
I just want to take focuses historically

**Comment by MasterWaifuman** [comment]
Like i said i added modifier to ai_chance that sets factor to 0 if historical on

**Comment by MasterWaifuman** [comment]
So it is in focus tree file in each focus that ai won't take if historical on

**Comment by MasterWaifuman** [comment]
I rechecked and tested it 3 times and NEVER belgium went lower than benilux focus. So this is not problem of the mod.
