### ISSUE TITLE
Consider adding Grand Duchy of Cracow as a puppet for Austria-Hungary

### ISSUE THREAD

**Issue by tkgalk** [Wolferos/Hearts-of-Iron-IV-The-Great-War#153]
https://en.wikipedia.org/wiki/Grand_Duchy_of_Cracow

It could be a nice beginning for a Polish focus tree and a nice way to "get Poland in the map" before the WW2 starts. Might be pretty interesting as Poland regained it's independence in 1918 (after WW1) and Polish fighters fought on all fronts (in Austria-Hungarian, Russian and German armies) with each country promising them independence.

Maybe playing as Grand Duchy of Cracow you could align with one of those three? Just an idea.

**Comment by MasterWaifuman** [comment]
There are some national focuses to get national states for Poland, and a player can free it by himself. But some sort of event that releases Poland in interwar period should do the thing.

**Comment by MasterWaifuman** [comment]
Not to mention Versailles Treaty, that releases Poland already exist.
