### ISSUE TITLE
mexico national focus

### ISSUE THREAD

**Issue by tallgo** [Wolferos/Hearts-of-Iron-IV-The-Great-War#161]
Hi, just found this mod and wanted to revive the mexican revolution, but when I try to choose to support the revolution (instead of siding with diaz) I cant. It says that Mexico needs to exist but it's crossed :c

**Comment by Wolferos** [comment]
Mexican National Focuses have been improved since

**Comment by Wolferos** [comment]
Mexican National Focuses have been improved since
