### ISSUE TITLE
Discussion about the Netherlands

### ISSUE THREAD

**Issue by Mixmaximonster** [Wolferos/Hearts-of-Iron-IV-The-Great-War#17]
## The Netherlands in the Great War
Hello there!
First of all: _Who are we_?
Well hello, I'm Redlink and I'm writing this on behalf of myself and Felicianum2.
We're two Dutch guys who are interested in the both World Wars.
The first time we played the great war mod we were impressed with the amount of content in this mod. 
We want to give people the chance to play as the Netherlands and have a interesting experience as the Netherlands because they played an interesting role in the Great war. 

We can't code but we have some suggestions for you to implement into the mod.
We've made a word document detailing a few events and a few example focuses (we will map and create a focus tree later)

Well now to wrap it up, If someone has idea's or suggestions for the Netherlands please tell us so because we are interested to hear what you guys have to say!

Well here is the file:
[The Netherlands Great War Mod.docx](https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/files/689730/The.Netherlands.Great.War.Mod.docx)

Goodbye!

Redlink 

## Things done so far:
**_(3 is finished, 2 is nearly finished, 1 is we're working on it, 0 is not started yet)_**
National focus tree  2
Events                      1
Leaders                    3
Borderconflicts       1

**Comment by Mixmaximonster** [comment]
Here are a few pictures in DDS format for the events (they are zipped because github wouldn't let me upload them)

If you need anything else, let me know.

[Pictures Events Netherlands WW1.zip](https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/files/689816/Pictures.Events.Netherlands.WW1.zip)

**Comment by Wolferos** [comment]
A quick summary about what was discussed on Steam.

- The Aceh war can be simulated with the "Border Conflict" System.
- The war starts directly and is ended via en event.
- Events in the documents are good
- Waiting more informations on the NF
- With the "Military Access" NF from Germany, maybe work something out here.

**Comment by Mixmaximonster** [comment]
We've started working out a national focus tree and we've completed the lay-out and general effects of the Political and Diplomatic tree.
Here is the layout:
![layout pol - dipl nf](https://cloud.githubusercontent.com/assets/24956529/21720624/836e9c54-d424-11e6-85d4-576d7e2906a2.jpg)
If there are too few or too many focuses with certain ideologies let me know and if there is just somthing missing or you think we've done it all wrong let me know!

abbreviations:
CEN - (join) central powers 
ENT - (join) entente
FRA - france
GER - germany
MIL - military acces
SUB - grants
NEU - Neutral

NOTE: most names arn't final and this isn't a detailed version of the focus tree

**Comment by DevilIris** [comment]
Tell me when is gonna be done the focus tree. So i can make it. Note: Will you add facist support? I don´t see any facist branch

**Comment by Mixmaximonster** [comment]
Alright we'll tell you, there is indeed no fascist branch, we talked to wolferos about that and we'll leave it out for now and add it later. And by the way, thanks @DevilIris  for making it :D

**Comment by Mixmaximonster** [comment]
@DevilIris You can start with these (i still have to do the rest)
![layout pol - dipl nf](https://cloud.githubusercontent.com/assets/24956529/21741801/7ecfab26-d4e1-11e6-85fd-5b8914940ca5.jpg)
Blue = Mutually exlusive
Purple = One of the above have to be completed
Red = normal
[NF effect NETHERLANDS.docx](https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/files/691523/NF.effect.NETHERLANDS.docx)
I've listed the effects of a few Nf's here, you can already start with those. 
**-The communist branch is included
-The Neutral branch is included**
The number at the bottom of the NF's is the AI factor.
The events arn't made yet but they will be very soon

**Comment by Felicianum2** [comment]
Hi I'm the co-writer of the tree,

I'm gonna give you information regarding the leaders and the parties from the Netherlands, as you probably know the leaders now used for the Netherlands are randomly generated (except for the queen of course).

**Democratic**
Leader: (Queen) Wilhelmina
Party: Algemeene Bond van RK-kiesverenigingen (ABRKKV) (I know it's a long name xD)
Popularity: 50%
![266px-wilhelmina1898](https://cloud.githubusercontent.com/assets/24975757/21742431/615fd936-d4ef-11e6-9ace-fbbb0db1d551.jpg)


**Authoritarian**
Leader: Abraham Kuyper
Party: Anti-Revolutionaire Partij (ARP)
Popularity: 24%
![abraham_kuyper_1905_ 1](https://cloud.githubusercontent.com/assets/24975757/21742422/33998970-d4ef-11e6-9695-74a718692b1a.jpg)


**Communist**
Leader: Pieter Jelles Troelstra
Party: Sociaal-Democratische Arbeiderspartij (SDAP)
Popularity: 26%
![266px-pieter_jelles_troelstra_1926](https://cloud.githubusercontent.com/assets/24975757/21742425/3cafe4e6-d4ef-11e6-99a9-de8228f4bd8e.jpg)


Greetings,
Felicianum2

**Comment by DevilIris** [comment]
You guys already did a lot of work and I just need to put the descriptions of the national focus tree . Are you doing it? also When will it be complete. So i can be able to add it

**Comment by Mixmaximonster** [comment]
Yup, I'm working on the rest of the focuses and effects I don't think I will get much more work done today but expect tomorrow atleast that whole picture of the tree done, then i'll start on the industrial branch etc.

**Comment by DevilIris** [comment]
The industrial branch always will be the generic one. I only need the political and diplomatic effort 
But if you want, you can change the name of the industrial effort etc.  and add a custom description

**Comment by Mixmaximonster** [comment]
Ah alright, but i can make a custom air - land - sea branch right?
Because there is some interesting stuff that can be implemented there (like fokker's designs he was a dutch man)

**Comment by DevilIris** [comment]
No, it will be the generic ones. But you can add a custom description example:  the focus tree of the Uk or mexico. You can add like france to develop their colonies in the political effort etc.

**Comment by Mixmaximonster** [comment]
Alright

**Comment by Mixmaximonster** [comment]
By the way, the NF's which add manpower are relatively high because the Netherlands don't have a big enough manpower pool to keep up with the major powers or even other minor nations for that matter. just a quick sidenote

**Comment by Mixmaximonster** [comment]
![layout pol - dipl nf](https://cloud.githubusercontent.com/assets/24956529/21745442/7a02fbb6-d52c-11e6-8a01-7c4b358a306e.jpg)
[NF effect NETHERLANDS (politcal branch).docx](https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/files/691734/NF.effect.NETHERLANDS.politcal.branch.docx)
Blue = Mutually exlusive
Purple = One of the above have to be completed
Red = normal

Alright in the file are all the effect of the political tree!
### Help wanted!
Would somoane please make the _"Netherlands requests Eupen"_ and the "_Netherlands asks Belgium to join faction"_ and the _"Netherlands asks Luxemburg to join faction"_ events
They fire with the corresponding NF's (Request Eupen) (Faction with Belgium) (Ask Luxemburg)
those NF's will be called something else but you'll have to look them up in the file for that
The AI factor for joining (both Luxemburg and Belgium) is 70 and declining 30 and giving Eupen is 40 and declining also 40

**Comment by DevilIris** [comment]
You have the events? also i need the diplo branch

**Comment by Mixmaximonster** [comment]
I don't have the events, i can't make them and I am working on the diplo branch but it will take a bit longer because of school

**Comment by Mixmaximonster** [comment]
the diplo branch is nearly finished and i'm working on it

**Comment by Mixmaximonster** [comment]
Oops

**Comment by Felicianum2** [comment]
Redlink and I discussed about alternate names and flags of the Netherlands when they are in power of the communist or the authoritarian regime, is it simple to implement this now in the game or do we have to wait for later updates?

**Comment by DevilIris** [comment]
You can pass me the flags in dds or tga with the same size so i can put them when i finish the national focus tree

**Comment by Mixmaximonster** [comment]
Alright nearly done with the Diplomatic focus tree and I've finished the events for the Political focus tree. (the events have to be put into the game first to let the focus tree work)
[EVENTS - Netherlands.docx](https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/files/697038/EVENTS.-.Netherlands.docx)

These are the pictures for the Potato revolution and for the "End of Census kiesrecht" event (the rest of the events don't need pictures)
[Pictures.zip](https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/files/697040/Pictures.zip)

**Comment by Mixmaximonster** [comment]
![political branch netherlands](https://cloud.githubusercontent.com/assets/24956529/21821601/75e758f2-d774-11e6-8377-398ab9e10b51.jpg)
This is the branch, I'm 50% on my way to finishing the effects. I won't finish it today but i think i'll get it done wednesday, otherwise it's thursday. (lot's of school stuff) (I'm sorry it's taking so long @DevilIris )

**Comment by DevilIris** [comment]
Yup no problem i finish the focus tree, added more generals anyways im fixing up now the xinhai revolution, the mexican revolution and the mexican focus tree.

**Comment by Mixmaximonster** [comment]
![diplomatic branch netherlands](https://cloud.githubusercontent.com/assets/24956529/21899290/021a8e62-d8f0-11e6-8d4f-9ae4ea988c4b.jpg)
[NF effect (Netherlands Diplomatic branch).docx](https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/files/702316/NF.effect.Netherlands.Diplomatic.branch.docx)
It's all done!
Legend:
Purple lines- One of the above is required
Red lines- All of the above are required
Blue lines- Mutually exlusive

**Comment by Mixmaximonster** [comment]
We have not thought of names for the generic trees yet though...

**Comment by Wolferos** [comment]
No problem, we can change them later.

**Comment by DevilIris** [comment]
Thx the netherlands NF is done

**Comment by Mixmaximonster** [comment]
Thank you for letting us make this @Wolferos and thank you for coding it @DevilIris !

**Comment by Mixmaximonster** [comment]
Hey, just curious to find out, when is the new update comming out? I'm guessing not since you just released one.

**Comment by DevilIris** [comment]
I don´t  know when is coming out, but we need to fix a lot of stuff also add new stuff , You can ask to @Wolferos , when is the new update coming.

**Comment by Mixmaximonster** [comment]
Alright, thanks!

**Comment by Wolferos** [comment]
The next major update will be the Open Beta 2.0, we don't have a release date for the moment. You can still download and test the lastest version on the homepage (https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/archive/develop.zip)


We're working on France leader of the Entente and reworking some war events, peace events, etc.

**Comment by Mixmaximonster** [comment]
Alright thanks i'll have a go at it ;D

**Comment by Mixmaximonster** [comment]
Hey all, I have a few small questions.
![schermafbeelding 2017-01-25 om 21 22 41](https://cloud.githubusercontent.com/assets/24956529/22307768/a2c0571c-e344-11e6-97ae-e51dbd3ac64f.png)
With that focus you can send volunteers more easily, but you can't even send volunteers without the correct spirit so shouldn't you get that as well then?

![schermafbeelding 2017-01-25 om 21 21 32](https://cloud.githubusercontent.com/assets/24956529/22307799/c1e77e86-e344-11e6-834b-1f9241470f9e.png)
I think this one a bit strange, a focus is not really worth doing for 10 manpower, it was supposed to give you some political power and 1 military factory in Java

![schermafbeelding 2017-01-25 om 21 21 55](https://cloud.githubusercontent.com/assets/24956529/22307840/e7a42a5c-e344-11e6-964c-d08b2239dcab.png)
The next focus "Home Defence" is supposed to remove "Neutral foreign policy"

![schermafbeelding 2017-01-25 om 21 21 41](https://cloud.githubusercontent.com/assets/24956529/22307881/175fc53a-e345-11e6-943c-f21ee26007a7.png)
And I think you forgot this focus because it's exactly the same as the one above it (this one is suposed to request eupen) 

and I havn't tested yet if the communist events fire but they probably do, 

Other then that, thanks for letting us help and you've done a great job!

**Comment by DevilIris** [comment]
@Mixmaximonster  that was the first version of the focus tree, i update that focus yesterday. I still working on the Holland focus, adding more stuff etc. I´m busy, making the focus for china and fixing the revolutions so i don´t have a lot of time to test that out

**Comment by Mixmaximonster** [comment]
@DevilIris Alright, thanks for letting me know and good luck with china!

**Comment by Mixmaximonster** [comment]
The communist tree is a bit underpowerd in relation to the other paths, it has 7 focuses and the other paths have 9 focuses, so i would like to add 1 or 2 extra. I havn't come up with anything yet though. I'll notify you when i've got them.

**Comment by DevilIris** [comment]
OK

**Comment by Felicianum2** [comment]
First of all, a great tree just like I expected it, but there is one small mistake I've stumbled on: the communist party name of the Netherlands isn't the right one. Now it's the CPN (Communistische Partij Nederland), but it has to be changed to SDAP (Sociaal-Democratische Arbeiderspartij). The CPN-party was founded after the great war.

**Comment by Mixmaximonster** [comment]
Hey!
@DevilIris 
These are some minor changes you can add (once you have time ofcourse)
Reduce communism gained from "end of census kiesrecht" NF from 20% to 10%
Reduce communism gained from "second reform" NF from 10% to 5%
Increase communism gained from "Let them eat potatoes" from 20% to 35%
Reduce minimum year for the "Let them eat potatoes" NF to 1915
Increase minimum year for the "Netherlands first" NF to 1914

(Some events arn't in the game yet and those which are didn't fire at all but you are probably aware of this)

Major changes:
add NF
Name: Paint the BeNeLux red
GFX_goal_generic_occupy_states_ongoing_war
PREREQUISITE: Troelstra's reforms
Description: Oh glory, oh glory! Workers all over the low countries feel free! Have faith in the revolution, have faith in us!
effect: Gains Puppet focus on belgium, Gains puppet focus on Luxemburg

**Comment by Mixmaximonster** [comment]
strangly my game keeps crashing around 14 april 1915 but Felicianum said that he didn't encounter that issue so it probably has to do somthing with my savefile or something

**Comment by Mixmaximonster** [comment]
Oh and by the way, we might be able to help you with making a focus tree for Belgium

**Comment by DevilIris** [comment]
That will be very nice let me finish the focus of china and fix the netherlands, mexico. And of course if you can help me making the belgium focus tree that be will very cool

**Comment by Mixmaximonster** [comment]
Alright, seems like you have a lot to do so good luck! (and thanks for letting us help ;D )

**Comment by DevilIris** [comment]
Finally i Update the Netherlands NF is you want to test. You are free to do it !

**Comment by Mixmaximonster** [comment]
Alright thanks!

**Comment by Mixmaximonster** [comment]
Hey, I see the events, the aceh border conflict and the party names didn't make it into the game.

**Comment by DevilIris** [comment]
the events are in the game

**Comment by Mixmaximonster** [comment]
Really? The 'end of census kiesrecht' and the bombing of Zierikzee and the Belgian refugees event chain didn't trigger for me

**Comment by Mixmaximonster** [comment]
Ah i see in the code that the 'end of census kiesrecht' event can be Triggerd if you are democratic but it should be communist too

**Comment by Mixmaximonster** [comment]
And i just noticed that the 'reform groot nederland' and the colony stuff is under communist but that wouldn't make much sense. When you create that faction in 1917 the war is already raging in that area and the entente would lose members. Also communists were against colonies so giving them colonial expansion isn't really logical

**Comment by DevilIris** [comment]
I was thinking adding them to a fascist branch, So i added to the communist branch, Is for give them more flavor to the game. Also i checked and the players like the NF whatever i will add more options in the future.
