### ISSUE TITLE
Triple Entente (French focus) duration 

### ISSUE THREAD

**Issue by notso5231** [Wolferos/Hearts-of-Iron-IV-The-Great-War#177]
![image](https://user-images.githubusercontent.com/39471458/41071644-1d77410a-69c7-11e8-8824-4c1205b0c915.png)

7 days, instead of 70. Does not appear to be intentional.

**Comment by Wolferos** [comment]
Duration time is now 14 days a06c044645da6dd8f52dc3dd4cf593c1d4f84e00
