### ISSUE TITLE
Russian Civil War

### ISSUE THREAD

**Issue by Wolferos** [Wolferos/Hearts-of-Iron-IV-The-Great-War#18]
When the White vs Red Civil War pops up, people experienced crash.
During our tests, we did not have a single crash.

Can someone confirm that the fix works?

Thanks

**Comment by DevilIris** [comment]
I tested already and i don´t have any crash in my game.

**Comment by FaccioFlatBread** [comment]
My game crashed while I was playing as Persia

**Comment by Wolferos** [comment]
@FaccioFlatBread Did you get the last version with the fix? (https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/commit/20e6ed689a590df23d847dc78c2f72f08e209ceb#diff-1a422ba2832e742dd12ef73b86859262)

It seems that the `division_template` was different from the other `division_template`.

**Comment by NotMatthewB** [comment]
My game does not crash but slows down massively when the event appears. I have a friend who has the crash occur still.

**Comment by Wolferos** [comment]
The massive slow down is "normal". The engine can't handle too many provinces switches. It depends on the computer power.

About the crash, it seems that it's a problem from the game itself, not the Mod. See the last Changelog of the Patch 1.3.2
- Fixed potential CTD in clearing country resources on civil war starts
