### ISSUE TITLE
Redrawing the Map

### ISSUE THREAD

**Issue by ghost** [Wolferos/Hearts-of-Iron-IV-The-Great-War#189]
As you may already know, the current map of the Game still uses vanilla Borders. Which means that Provinces are still taylored towards a WW2-setting. This obviously means that most in-game borders are historically inacurrate (look no further than the Balkans - there is almost no correct pre 1936-Border there and everything looks janky and weird)

For the last few days I have worked on a Map file based on an earlier scrapped project of mine. The map now contains a large number of new Provinces and also changed many province borders which should depicte accurate 1910s borders. Of course, there are still certain things missing, but if the Team would be interested, I could upload the files here.

A few examples:
![20190203151529_1](https://user-images.githubusercontent.com/38785198/52177851-4c160f00-27c7-11e9-97b2-6a06f47eae99.jpg)
The Balkans before

![20190203150843_1](https://user-images.githubusercontent.com/38785198/52177857-5df7b200-27c7-11e9-8ec5-b8af41bc91ce.jpg)
The Balkans After

![20190203151845_1](https://user-images.githubusercontent.com/38785198/52177839-343e8b00-27c7-11e9-86c8-a9f9d714b62f.jpg)
West Africa before

![20190203150924_1](https://user-images.githubusercontent.com/38785198/52177843-3bfe2f80-27c7-11e9-8ffe-4ecd433f2dd2.jpg)
West Africa after

Close-Up of South Africa before and after:
![20190203151812_1](https://user-images.githubusercontent.com/38785198/52177859-723baf00-27c7-11e9-814c-cee928df5994.jpg)
![20190203150347_1](https://user-images.githubusercontent.com/38785198/52177861-736cdc00-27c7-11e9-92ae-247a940f09ac.jpg)

Austria has mountainous Borders now and the province's shapes more closely resemble its historic Subdivisions:
![20190203150610_1](https://user-images.githubusercontent.com/38785198/52177878-98614f00-27c7-11e9-83f5-92b816b131bd.jpg)

The most important changes include:
New Provinces in Latin America, Africa, the Middle East, the Balkans and in some other dispersed places (e.g. Iceland or Kashmir)
States have been changed to fit the new Borders (no new States have been included though)
New Sea Passages and Mountainous Borders (especially within Europe and Asia)
Existing Provinces have been redrawn to more closely fit Borders and historic Claims of the time.
All Unit and Buildings Placements have already been updated.

The Map already works with the Mod. So far, i haven't encountered any major issues.

**Comment by Fordin** [comment]
Don't forget Germany's borders which have been obvious since the dawn of time
![why](https://user-images.githubusercontent.com/48535823/54320577-d53d1480-45c3-11e9-93be-48982f0cf303.jpg)

This bugs the living hell out of me, especially backed up with the fact that Paradox itself fixed this.

**Comment by ghost** [comment]
Don't worry, this border has also been fixed. I couldn't change every border as the map doesn't include any new states, which somewhat limits my possibilities
Rn, I'm still waiting for any sign of official approval but the devs seem to have set their priorities completely towards their new game.

**Comment by YuiSakyubasu** [comment]
It would be great if you uploaded the new map. The current one has the 1936 borders and it even has some errors.
