### ISSUE TITLE
West Banat is unowned

### ISSUE THREAD

**Issue by YuiSakyubasu** [Wolferos/Hearts-of-Iron-IV-The-Great-War#192]
The state of West Banat is non-existent. It's a problem if you want to play as Austria-Hungary, Serbia and Balkan powers in general.
![image](https://user-images.githubusercontent.com/49311269/55629523-afb2bd80-57b3-11e9-889b-36d23c73965f.png)

**Comment by Wolferos** [comment]
This problem has been fixed 98409c4fa7dd0b079ec0434990945c1ccc9f9e95 (integrated in the Open Beta 0.7.3), thanks @YuiSakyubasu for your bug report 👍
