### ISSUE TITLE
Puerto Rico as a puppet of USA ??

### ISSUE THREAD

**Issue by FaccioFlatBread** [Wolferos/Hearts-of-Iron-IV-The-Great-War#20]
Hello I was wondering if there was any chance that your team can feature Puerto Rico as a puppet of the United States ( I can also do it myself since i have a bit of experience in modding for hoi4 and I would be qualified for the role of modding i Puerto Rico since I am Puerto Rican and know a lot about its history ). I can also help out with the Spanish translations if needed.

Thank you

**Comment by DevilIris** [comment]
Fundación de puerto rico
Estado libre asociado: 25 de julio de 1952,  no seria correcto ya que es un mod de la primera guerra mundial  debe de ser una colonia de estados unidos como filipinas en ese momento.

**Comment by Wolferos** [comment]
Hello

Puerto Rico was part of the United States (https://en.wikipedia.org/wiki/Treaty_of_Paris_(1898)) until 1952. We won't put them as Puppet because it would require creating a whole new country.
