### ISSUE TITLE
Fixed Ship port and can´t move them from it.

### ISSUE THREAD

**Issue by oKhanToTh** [Wolferos/Hearts-of-Iron-IV-The-Great-War#202]
As I played as Brazil, as I did before I always start building the regular submarine first but everytime and every ship I try to build (with or without mods) they end up on the same por - even if they are "told" to spawn on another port. It cannot move form this port or take battle formations. Although, the ships the country already starts with are free to move and battle the ones created from there cannot. Hope I could help better, just ask for more info if necessary.

**Comment by Wolferos** [comment]
Fixed in 6527405268c72e1385f0e61bf5ede3837cbae76b thanks @oKhanToTh for this bug report 🦸‍♂️

**Comment by oKhanToTh** [comment]
@Wolferos Many thanks for your help, I will try it now!
