### ISSUE TITLE
Unique & Generic National Focus

### ISSUE THREAD

**Issue by Darksaber501st** [Wolferos/Hearts-of-Iron-IV-The-Great-War#21]
Hello

So this is a question to anyone who knows more about the final intended release of this mod. What is the actual plan/goal for national foci? Most countries currently have a relatively similar national focus tree for this mod, with some unique politics and development options but very similar things for army, navy, air force, and industrial development. Is the goal eventually to change that? And if so, what would be changed? Is the plan to shift stuff around and make those areas less uniform by making paths and results nation-unique as in the internal/external politics area, or is it simply to keep it the same layout but eventually give each country unique flavor text?

The reason I ask is that I'm not sure that either unique setups or unique flavor text for most of those is really necessary, since I think a lot of countries were struggling with the same core set of issues as they transitioned from older styles of warfare to new ones. Obviously, each country deserves some uniqueness,, but if they're going to have the same effects, do we actually want to give each country unique flavor text? And pretty much everyone was struggling equally to ramp up their industrial base to the scale necessary and also provide the newest level of lethality to their troops. We probably do want some unique focuses for each country in each of these sections (i.e, the Russian European/Asian naval dilemma being an excellent and well-designed example), but how many?

I'm sure some people have already had this discussion, I'm just new, so I'm curious if there were any specific plans or goals that had been decided upon. Thanks!

**Comment by Wolferos** [comment]
Hello

The idea is to have a NF for all Majors and Minors countries based on the same structure, **6 Pillars**:
1. Political
2. Diplomatic
3. Land
4. Air
5. Navy
6. Industry

The 1. and 2. can be personalized to represent at the best the situation of the country in 1910 and be unique.
The 3., 4. and 5. stay generic but with a small personalization on the Texts and Effects and also like you said about Russia, some choice to make.
All this lay on the concerned country and its history.

Kaiser made generic descriptions (for 3., 4., and 5.) that will be put in all the NF.

**Comment by Darksaber501st** [comment]
Awesome, thanks for the clarification. I had seen some of the generic descriptions, but wasn't sure if they were the final thing or not since they weren't in most of the country localization files where the focus names were. I had thought about writing some of the descriptions, but didn't want to spend a lot of time on it unless it was necessary, and it obviously is not except for adding some for the unique NF of each country.

Is the goal for NF trees to have all of them eventually extend all the way through the interwar period and to WWII? Or is it just WWI for now?

**Comment by Wolferos** [comment]
For now, the main focus is the WW1 and Peace Events.

Here's a quick summary of what we need to do :
- Put France Leader of the Entente. It's something that we will do (Wolferos Team) because it implies to modify a lot of scripts, events and NF.
- NF for Soviet Union
- NF for Greece
- NF for Romania
- NF for Belgium
- New NF for Russia (note that we have the plans made by Kaiser)
- Several Peace Events for each side with a lot of "what if" cases.

Interwar Period and WWII are to be considered at an experimental stage. We wanted te see the amount of work that it would require.

**Comment by Darksaber501st** [comment]
OK, I'll take some time this weekend and look at the Soviet Union, if no one else has already done it (I'm new to GitHub, so if there's a task-assignment area here, I have yet to find it). There are so many exciting possibilities with the SU.

If someone has worked on it already or currently is, let me know and I'll look at peace events. Those are always fun to think of and script.

**Comment by Wolferos** [comment]
The SOV is free. You can create a new issue for it and i'll assign it to you.

Regardings events, there is already the October Revolution, the Russian Civil War (White vs Red) and the Polish–Soviet War (Interwar Period).
