### ISSUE TITLE
Lack of portrait makes political advisors unselectable

### ISSUE THREAD

**Issue by i72jilej** [Wolferos/Hearts-of-Iron-IV-The-Great-War#212]
**Description:** When hiring a political advisor if he doesn't have a portrait (not even the "?" picture), once hired he can't be interacted with again, making it impossible to hire a new one or to see his description.

**Reproducing the bug:**
![20200122133156_1](https://user-images.githubusercontent.com/9350661/72894685-2f4a5280-3d1c-11ea-9541-889e37ad1b19.jpg)
Here, Joaquín Ruiz doesn't have a portrait. You can however hire him

![20200122132616_1](https://user-images.githubusercontent.com/9350661/72894833-6b7db300-3d1c-11ea-9561-45f7453d2780.jpg)
Once hired, he can't be selected again. In this picture, the mouse is over that second political advisor and no tooltip appears and cannot be clicked.

**Comment by Wolferos** [comment]
We'll investigate this bug, thanks for your report @i72jilej

**Comment by Wolferos** [comment]
[FIXED] Joaquín Ruiz has now a Portrait 9e54874240428ff3f0fcf6504d41e21f2a946a91
