### ISSUE TITLE
Early War Ships Should Use Coal, Not Fuel

### ISSUE THREAD

**Issue by sgerhardt** [Wolferos/Hearts-of-Iron-IV-The-Great-War#213]
### Problem:
Ships use oil when they typically used coal in the early time period. See https://en.wikipedia.org/wiki/Dreadnought#Fuel

There's an abundance of coal resources in the game, and I'm not sure what exactly they're being used for. Seems like ship fuel would be an appropriate use. 

A few questions that would need to be answered:

1. What is the exchange rate for coal to oil? It's not 1 to 1. Oil has roughly twice the thermal content of coal, so maybe 2 to 1 would be acceptable. There is much more coal available than oil - so not sure what game play impacts this may have yet. This needs to be answered so an appropriate burn rate can be established. 

2. What model of ship should start using oil? In 1912, the UK started to use oil on its own in the Queen Elizabeth class. The US, having an abundance of oil, started its own aggressive oil based naval building program around this time as well.

3. Is it possible to have ship models that burn both fuel and coal? This would reflect reality for many ship models, though it needs to be determined if the game supports this.

**Comment by Wolferos** [comment]
Excellent remark @sgerhardt but sadly _Fuel Usage_ in **Hearts of Iron IV** is an engine-coded stat.

About that, in **Fields of History** ships can consume _Fuel_ or _Coal_! 👍

For the Mod, what we can do it's to add _Coal_ as a needed Resource for the Construction of the oldest ships. It's not a perfect solution but it's a bit more "historical" that way.

**Comment by Wolferos** [comment]
Coal, Wood and Oil have been added in order to build some Ships in the _Open Beta 0.9.1_ 😉 @sgerhardt
