### ISSUE TITLE
Update Picture's of Leader's / General's

### ISSUE THREAD

**Issue by Helites** [Wolferos/Hearts-of-Iron-IV-The-Great-War#22]
Hi i have Two Pictures that i want to upload to your mod.

SWI_Ulrich_Wille.dds (FieldMarshal) and SWI_Robert_Comtesse.dds (Leader). How do i do that? 
I have already requested some Changes on SWI-Switzerland.txt.

Best,
Helites

**Comment by Wolferos** [comment]
Hey

Here's how to make a Pull Request so that we can integrate your work: https://help.github.com/articles/creating-a-pull-request/
