### ISSUE TITLE
Crash during game launch

### ISSUE THREAD

**Issue by TethysGrim** [Wolferos/Hearts-of-Iron-IV-The-Great-War#222]
Every time I have tried to launch this game, I've gotten a crash during the loading screen. From what I've seen in the Steam forum, this issue is affecting many other people as well. Since this completely prevents the mod from being used by those affected, fixing this should probably be top priority.

**Comment by Wolferos** [comment]
Hey @TethysGrim!

Do you still have this problem with the latest update of the Mod (Open Beta 0.10.3)?
