### ISSUE TITLE
SOV National Focus Ideas

### ISSUE THREAD

**Issue by Darksaber501st** [Wolferos/Hearts-of-Iron-IV-The-Great-War#24]
So over the course of this weekend, I'll be working on the NF tree for the Soviet Union.

The Soviet Union is a bit unique here, since they're probably not going to pop up until 1916 at the earliest, and having a NF tree full of major things that take 70 days would leave them in a little bit of a scramble to catch up to the other powers, though historically they took they time to focus internally I wanted to leave plenty of room for an overly ambitious player to bring them back onto the world stage very quickly. Therefore, while there are a lot of options, some things like most of the "Complete the Revolution" focuses or "Execute the Imperial Family" will be relatively short in duration.

Below is my first pass at a Soviet political NF tree. I obviously haven't coded it yet, and I'm happy to hear people's thoughts before that gets underway. I'll post something about diplomacy tonight or tomorrow.

![sov_nf_political](https://cloud.githubusercontent.com/assets/24844350/21935514/d5e7d246-d97b-11e6-8b00-95fa6f625418.JPG)

What I had in mind:

Three unique directions for the player to focus on: External (i.e., anti-White) defense, internal purification, and revolutionary rollback.

**Going left to right: Defend the Revolution branch**
- National call for Volunteers would give a new national spirit with a reinforcement bonus and recruitable population bonus for the duration of the Civil War. Perhaps load an OOB via an event.
- Execute the Imperial Family (drastic, but historical, let me know if that's beyond limit of acceptability and I'll understand). This would dramatically lower the opinions of several countries (UK, Denmark) to which the Romanovs were related, and also generally lower world opinion, but would increase national unity. Only available if you pick the hardline Bolsheviks in the "Complete the Revolution" tree.
- "Claim Victory" if the White Movement has been destroyed, national unity bonus, perhaps a new national spirit "Successful Revolution". I currently have this after "Execute the Imperial Family" because I think that the idea of the White Movement would always live on if most of them survived. Perhaps do occasional White uprisings if this or the Cheka aren't completed. Should give some political power.

**Next up: Complete the Revolution branch**
- Support the Bolsheviks, mutually exclusive with:
- Support the Mensheviks
I don't think it really matters, because I think given the opportunity to corrupt themselves the Mensheviks would have gotten equally bad, but the result of choosing the Mensheviks would be a leader change and NU increase, and choosing the Bolsheviks keeps Lenin but you get a drop in NU due to socialist infighting. Maybe a temporary national spirit of "Socialist Infighting" here. Both should also give political power.

_Either way, it continues with_
- Establish the Cheka: NU drop, but lowers partisan and subversive activity effectiveness, and gives a national spirit "The Cheka" to do so. Should also give some political power.
- The Red Terror: Temporary National Spirit, NU drop, but ends any possibility of a revolt for the time being. This might be better served as an event chain after the Cheka. I'm also thinking it can lead to the independence of Finland.
- Set up the GULAG: Available only after end of Civil War. Creates some factories in Siberia, increases political power, lowers NU.

_A side branch to "Complete the Revolution:"_
- "A Soviet Constitution": NU Boost, political power drop, but opens the way for "Worker's Paradise" later on

**Final branch: "End the Revolution" (the thought being it has gone too far, perhaps)**
- Embrace Liberty, increases support for Democratic, mutually exclusive with Embrace Authority. Also sets up elections! Also may allow for Finland's independence.
- Foster New Values: PP drop, NU increase (can come from either "A Soviet Constitution" or "Embrace Liberty." Also may allow for Finland's independence.
- Embrace Social Welfare programs: Increases demand for consumer goods, NU boost
- Worker's Paradise: Shift to undisturbed isolation, disarmed nation, closed economy, as Russia becomes a utopian Communist state.

-Strengthen the Duma: PP drop, leader change to someone more Democratic. Allows for the invitation of the Romanovs to return in a lesser role, assuming you didn't murder them.

_The other half of "End the Revolution" would be:_
- Embrace Authority: Increases support for Authoritarian, NU boost and PP drop. Allows players to move the country back to a more authoritarian or even fascist worldview.
- Restore Imperial Glory: Big boost in support for authoritarian, NU drop, PP drop. Also may allow for Finland's independence.
- Invite the Romanovs to Return. They would do so as a National Spirit, similar to many of the other monarchs from the base HOI4, given that the country is now much more liberal.

- End Heretical Rule!: Increase support for Fascism. NU boost, PP drop, but represents a shift towards non-Tsarist authoritarianism.
- A New Russia: New leader, party switches to Fascist. Also may allow for Finland's independence.

**Comment by Darksaber501st** [comment]
As promised, here is a first pass at a SOV diplomatic tree. Again, please feel free to provide comments. I'll start coding the basics this weekend and continue this week.

![image](https://cloud.githubusercontent.com/assets/24844350/21955268/77b3ac76-da35-11e6-80b4-5049a85dee31.png)

What I have in mind: Two initial branches, "Respect the Treaty" and "Break the Treaty", or in other words give the player an option to rejoin the war that the AI will never take.

**Going left to right: Respect the Treaty branch**

First, Repect the Treaty gives a diplomatic boost to all members of the Central powers and a diplomatic malus to all members of the Entente, plus a small NU boost (I know I use NU boosts a lot but I think SOV's NU should be slow to start and have lots of little NU boosts as it turns into a real country)

_The primary branch that requires respecting the treaty is the "Restore Order Branch"_
- Restore Order: Focuses on quelling dissent in the various Soviet Republics. Failing to take this should lead to independence fights from Gerogia, Armenia, Kazakhstan, etc., should renewed warfare go poorly.
- Focus on Collectivization: Slight NU drop as farms are seized, some dissent in agricultural regions TBD, but a small increase in recruitable population and/or slight decrease in consumer goods demand.
- Rebuild our Industrial Base: Much harder than seizing some peasant farms, SOV needs to start creating and modernizing the heavy industry it is known for. NU drop, but gives us some civilian factories in random states.
- Siberian Development: This will require the "Gulag" national spirit from the political chain. It should add a factory or two, representing non-forced settlement in the interior.

_The next two branches can be from either respecting or breaking the treaty of Brest-Litovsk, the first is the "Revanchism" branch_
- Revanchism: Small NU boost and recruitable population boost. Allows for SOV to begin trying to recover both lands lost by RUS (the "Assert our Claims in Asia" focus), as well as territory lost during the Russian Civil War.
- Assert our claims in Asia: NOTE: This should be automatically completed (complete_national_focus command) if RUS did this. PP boost.
- Prepare our Eastern Defenses: Similar to the above focus, should be completed automatically if "Reinforce Vladivostok" is done. Has same effect.
- Revenge on Japan: Similar to "Revoke Treaty of Portsmouth", gives a conquer CB against Japan. This should not be automatically done, as a new government will have new priorities.

If this were to be extended to the Interwar period, I'd include more about the Chinese Civil War and such. but I think this is pretty good for a country that starts between 1915 and 1917.

- Intervene in Finland: NOTE: This should not occur if Finland is somehow a German puppet. I'm thinking about adding a Finnish Civil War event, where the Finnish Reds could become a SOV puppet instead of outright annexation should they win after "The Third International", or otherwise they'd just get annexed.  This focus would add Finland to the White Movement and create a Conquer CB on Finland to make it easy for SOV to intervene. Any intervention should bring about a significant NU drop, and should trigger an event giving Finland a massive set of nationalistic boosts to allow themselves a chance against SOV. It'd be bypassed if Finland is a German puppet or the Finnish Civil War is already over. Ergo, this is available for completing either Revanchism or The Third International.

- Ukranian-Soviet War: Very similar to the "Intervene in Finland above", should be allowed if Ukraine is in its own Civil War. If SOV wins, Ukrainian SSR should either be puppeted (with Third International) or annexed (without).
- Polish-Soviet War: Conquer or Puppet CB on poor Poland. Would give Poland an event National Spirit and lots of bonuses to survive. If SOV wins, Polish SSR should either be puppeted (with Third International) or annexed (without).

**The other main direction is: Break the Treaty.**
It gives a diplomatic malus to all members of the Central powers and a diplomatic boost to all members of the Entente, plus a significant NU drop.

_The other of the two central branches is "The Third International" branch_
- The Third International: Creates the Comintern faction, PP drop
- Export the Revolution to Europe: All European countries get an event either allowing for slightly increased Communist support for 2-3 years or increased dissent. PP drop for SOV. Diplomatic malus with any affected country.
- Export the Revolution to Asia: See previous, but for Asia.
- Export the Revolution to the Americas: See previous, but for the Americas. Lots of Anger from the USA.

_The final branch is the branch for re-entering the war_

- Contact the French: PP drop, diplomatic boost with France, as SOVs negotiate how they rejoin the war.
- Prepare our People: PP drop, big NU boost as Soviet propoganda focuses on defeating the vile Germans. 
- Rejoin the Entente: Obvious.
- Revenge on Germany: Gives a Puppet CB for Germany, if they haven't already DOW'd you.

**Comment by DevilIris** [comment]
If you will rework russia check this  : [https://www.youtube.com/watch?v=JpycUBpgWzU](url)
