### ISSUE TITLE
Issue with Serbian parties

### ISSUE THREAD

**Issue by oksel99** [Wolferos/Hearts-of-Iron-IV-The-Great-War#243]
I really like your mod and if I can contribute a little I would suggest that you change the parties for Serbia, because those in the game are from WW2 not WW1. 

The majority party before and during WW1 was the National Radical Party (not Mihajlovicevi cetnici - this wasn't even a party). 

And there was no Communist party in 1910 but there was the Serbian Social Democratic Party and later after the Russian Revolution this party became Communist.

The third was the Serbian Progressive Party. 

I could help more but I don't know if you accept help.

**Comment by Wolferos** [comment]
Thank you @oksel99 for your suggestions! We'll integrate them :+1:

**Comment by oksel99** [comment]
Thanks I am glad :) So National Radical Party was democratic,   Social Democratic Party was leftist later Communist, and Serbian
Progressive Party somewhat nonaligned.
