### ISSUE TITLE
Britain has 1918/19 tech in the May 1914 start

### ISSUE THREAD

**Issue by alexwesterberg** [Wolferos/Hearts-of-Iron-IV-The-Great-War#282]
Choosing the 1914 start, playing as Great Britain, you have unlocked tech from most of the 1918/19 eras in the tech tree. I assume this was meant to be the techs you start with on the 1919 start.

Example: 

![20210517222431_1](https://user-images.githubusercontent.com/60098965/118558731-f464fd00-b75e-11eb-926a-705600a3e655.jpg)

N.B. it is not just infantry tech; artillery, support, armor, land doctrine, all naval, air and industry is also teched up.

Have tagged each of the other powers for the 1914 start and none of them experience this issue.

Seems like a simple misallocation of the file for unlocked tech, hopefully an easy fix?

Thanks for a superb mod btw, keep it up!

**Comment by Wolferos** [comment]
Thank you for the bug report! The technologies have been assigned and the issue should be fixed 😉
