### ISSUE TITLE
Britain Starting out as Entente in 1910

### ISSUE THREAD

**Issue by AwareWoIf** [Wolferos/Hearts-of-Iron-IV-The-Great-War#29]
I don't think Britain should start automatically in an alliance with France. Considering that, in our time line, Britain only declared war on Germany because the Germans invaded Belgium, Great Britain should only be automatically called into war if Germany adopts that strategy.

The invasion of Belgium violated the Treaty of London, signed in 1839, which was Britain's main justification for war with Germany. While the AI Germany might always take this option, when I played as Germany I didn't, yet still found myself at war with Britain, and at peace with Belgium.

**Comment by Wolferos** [comment]
Hello

It's already planned, we are working on it. France will be Leader of the Entente and UK will have a choice to defend Belgium and join the Entente or stay out of this.

**Comment by Wolferos** [comment]
Fixed in the 0.2
