### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by AlainEtCo** [Wolferos/Hearts-of-Iron-IV-The-Great-War#37]
Hi
I have traduced some files in french.
I will do the other one "quietly" time to time..... :)

Tell me if you need some particular thinks.

(My english is most "Globish", so apologize for the mispelling or other clumsiness.... )

Alain.

**Comment by Wolferos** [comment]
Salut !

Vu que cela concerne la traduction française (et donc pas directement nos amis anglophones), nous pouvons parler en Français pour se faciliter la tâche.

Une autre personne travaille également sur la traduction, @Polemarque de MundusBellicus.Il a traduit le NF des USA ([ref](http://www.mundusbellicus.fr/forum/espace-communautaire/p%C3%B4le-de-traduction/527183-hoi-iv-the-great-war-traduction-du-mod?p=530415#post530415)) et fera bientôt je pense son Pull Request.

**Comment by AlainEtCo** [comment]
Bonjour !

Ok je prend bonne note pour le français.

Bien, je continuerais à remonter doucement dans l'arborescence pour faire les "petits" textes pour l'instant. 

Si @Polemarque se manifeste, nous verrons de nous partager les tâches histoire de ne pas se marcher sur les pieds :)

A bientôt.

**Comment by Polemarque** [comment]
Content de vous rejoindre :)
J'ai galéré un peu pour trouver comment faire, mais je viens d'envoyer la pull request. J'espère juste ne pas avoir fait d'erreur en utilisant l'interface de Github, je découvre a peine ce site. 

Pas de problèmes pour se partager les tâches; je travaille avec HoI IV ouvert à côté avec le mod. Je pensais faire la prochaine traduction sur les textes de présentation des pays, à l'ouverture du mod. C'est bon?

**Comment by AlainEtCo** [comment]
Salut !
Ok pas de soucis ! 
A la limite inscrit le nom du fichier à la suite.
Je ferais de même quand ce sera des trucs un peu long. 
Pour le moment, je ne fais que les "petits" fichiers que je trouve entre midi et deux au taf...

Pour les travaux un peu plus long, je noterais aussi le fichier sur lequel je suis en train de bosser. 

A bientot !

**Comment by Polemarque** [comment]
Entendu; je préviendrais quand il s'agira de travailler sur des textes longs.

**Comment by AlainEtCo** [comment]
Salut à tous.

Je n'abandonne pas le morceau, c'est juste que je suis "hypra" occupé en ce moment :)

A tés bientôt.

**Comment by theroxas898** [comment]
bonjour a tous, j'aimerai pouvoir apporter mon aide à ce projet de traduction, pourrait on m'expliquer comment m'y prendre?

**Comment by Mindeufair** [comment]
Euh... j'ai fait une traduction, mais je ne sais pas comment la proposée, je me suis inscrit sur GitHub pour traduit ce mod, je ne sait pas trop comment ça marche ^^

**Comment by Mindeufair** [comment]
Je vais essayer de faire quelques petits textes, j'ai déjà traduit les rangs, je voulais juste une clarification de la façon dont marchent les "Pull requests". Merci d'avance !

**Comment by Polemarque** [comment]
C'est relativement simple une fois qu'on a pris l'habitude, mais c'est vrai qu'un petit tuto français ne serait pas de trop! Pour traduire (corrigez-moi si je me trompe), il faut aller dans "mod", puis "thegreatwar", "localisation", et là on a accès à tous les textes du jeu. Il faut en choisir un et cliquer dessus, puis sur le bouton "edit this file", après quoi on a accès au texte. Plus qu'a bosser et traduire le texte entre les guillemets, et ne pas oublier de changer "english" dans le titre en haut à droite par "french". 
Ensuite, cliquer sur "propose file change" en bas de l'écran, puis sur "create a pull request" sur l'écran qui s'affichera ensuite.

**Comment by Polemarque** [comment]
J'ai oublié de préciser: il faut aussi changer "english" par "french" dans les premiéres lignes de code au début du fichier!

**Comment by Mindeufair** [comment]
Très bien, merci beaucoup ^^

**Comment by Mindeufair** [comment]
Je propose de commencer à traduire ww1_bookmarks_l_french, soit les messages d'introduction du jeu. Cela fera déjà plus "propre" pour la vf ^^

**Comment by AlainEtCo** [comment]
Ok !
Je suis un peu trop occupé en ce moment, je verrais de continuer de traduire les petits bouts de fichiers qui reste à l’être. 

Je me trouverais du temps pour aller plus avant dans 1 semaine ou deux.

**Comment by Mindeufair** [comment]
Peut-on introduire une traduction française des noms des dirigeants dans le mod ? Je n'ai pas trouver de fichier dans "localisation".

**Comment by Felixiinho** [comment]
Bonjour à tous!
  
J'aimerais participer à la traduction de ce très bon mod, je me permets de demander si vous avez besoin d'aide supplémentaire?
Si oui je me pose quelques petites questions sur le fonctionnement de github ^^

D'après l'explication de Polemarque, je résume pour être sûr de la marche à suivre ^^
-on doit aller dans l'onglet code/mod/thegreatwar/localisation/
je prends en exemple le 1er fichier(déja traduit en fr) "autonomy_l_english.yml" donc j'aurais cliqué dessus puis sur le bouton "edit this file" puis traduire le texte entre les guillemets, puis le titre qui serait devenu "autonomy_l_french.yml" et ensuite, cliquer sur "propose file" change en bas de l'écran, puis sur "create a pull request" sur l'écran qui s'affichera ensuite comme la très bien expliqué Polemarque!


Dites moi si j'ai loupé quelque chose ^^
Merci d'avance.

**Comment by Polemarque** [comment]
Oui, a priori c'est ça. Mais ça serait bien qu'un "ancien" vienne le confirmer; je n'ai que quelques semaines d'ancienneté par rapport à vous. 
@Mindeufair par contre j'avais déjà commencé a travailler sur la traduction de ce fichier! Je comptais le mettre en ligne cette semaine; t'en es où toi?

**Comment by Mindeufair** [comment]
En fait je demandais justement le nom du fichier (si tu parles bien des noms des dirigeants) donc si tu l'as déjà traduit c'est parfait

**Comment by Mindeufair** [comment]
Sinon si tu parles des textes d'intro je les ai déjà finis (dans ce cas désolé) comme le Japon n'avait aucun texte d'introduction en aucune langue, je les ai créés

**Comment by Polemarque** [comment]
C'est pas grave, l'essentiel c'est qu'il soit fait!

**Comment by Mindeufair** [comment]
Tu pourrais me passer ta traduction ? Comme ça je pourrais comparer et si certaines de tes traductions me semblent mieux que les miennes, je les utiliserai.

**Comment by Felixiinho** [comment]
D'accord merci! Je vais me lancer sur ww1_nf_auh_l_french.yml comme le fichier existe déjà mais pas traduit,  normalement je pourrais pas faire de mal ^^

**Comment by AlainEtCo** [comment]
J'ai commencé =>  bookmarks_l_french.yml, le fichier est créé et j'ai commencer la traduction.
Voir dans les pull request et le commentaire que j'y ai laissé... Je sèche sur un truc :)

A bientot !

**Comment by Polemarque** [comment]
Est-ce qu'une mise a jour prochaine du mod est prévue? Bon nombre de fichiers texte sont déjà traduits, il devient difficile de s'y retrouver et de savoir quel fichier reste a traduire ou pas.

**Comment by Wolferos** [comment]
Une mise à jour est prévue pour la sortie du Patch 1.4 "Oak"

**Comment by Mindeufair** [comment]
Bonjour à tous, je tiens à préciser que nombreux sont les fichiers à traduire déjà présents dans le jeu de base, je conseil donc d'effectuer un copié-collé de ces traductions bien réalisée, cela évite une perte de temps inutile. Il faut juste être attentif au fait que Wolferos n'ai rien ajouté, il faudrait dans ce cas traduire ce qui n'est pas présent en vanilla dans le fichier

**Comment by Polemarque** [comment]
Bonjour,

Je me posais la m&ecirc;me question car certaines traductions sont extr&ecirc;mement longues &agrave; faire. On sait o&ugrave; r&eacute;cup&eacute;rer ces lignes de texte? 
Le mail n'&eacute;tait pas fini, tu disais "tout en veillant au fait que Wolferos"...?
 
Cordialement

----- Mail d'origine -----De: Mindeufair <notifications@github.com>&Agrave;: Wolferos/Hearts-of-Iron-IV-The-Great-War <Hearts-of-Iron-IV-The-Great-War@noreply.github.com>Cc: Polemarque <th.buchet@laposte.net>, Mention <mention@noreply.github.com>Envoy&eacute;: Wed, 12 Jul 2017 00:13:20 +0200 (CEST)Objet: Re: [Wolferos/Hearts-of-Iron-IV-The-Great-War] French translation (#37)

Bonjour &agrave; tous, je tiens &agrave; pr&eacute;ciser que nombreux sont les fichiers &agrave; traduire d&eacute;j&agrave; pr&eacute;sents dans le jeu de base, je conseil donc d'effectuer un copi&eacute;-coll&eacute; de ces traductions bien r&eacute;alis&eacute;e, cela &eacute;vite une perte de temps inutile, tout en veillant au fait que Wolferos
&mdash;You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Mindeufair** [comment]
Oui en effet, vous avez reçu la notification du message que j'ai mis sur le
forum, je l'ai involontairement envoyé avant d'avoir fini, le message
complet est celui-ci : "Bonjour à tous, je tiens à préciser que nombreux
sont les fichiers à traduire déjà présents dans le jeu de base, je conseil
donc d'effectuer un copié-collé de ces traductions bien réalisée, cela
évite une perte de temps inutile. Il faut juste être attentif au fait que
Wolferos n'ai rien ajouté, il faudrait dans ce cas traduire ce qui n'est
pas présent en vanilla dans le fichier"

cordialement ^^

**Comment by Polemarque** [comment]
Houlà, le mail a mal passé. Je voulais dire: "Je me posais la même question car certaines traductions sont extrêmement longues. On sait où récupérer ces lignes de texte?" Pour la VF du jeu de base. 

Tant qu'on y est, je voudrais signaler que je travaille actuellement à la traduction de deux très gros fichier, equipment_l_french.yml et ww1_events_l_french.yml; comme ils sont particulièrement longs et que j'ai déjà pas mal avancé, inutile que quelqu'un s'y lance aussi. Je ne peux pas avancer de date, mais a mon avis c'est une question de semaine pour leur achèvement.

**Comment by Mindeufair** [comment]
Pour la localisation des fichiers c'est très simple : dans Steam vous faites clic droit sur votre jeu, puis "propriétés", dans la fenêtre qui s'ouvre vous ouvrez le menu "fichiers locaux" et enfin "parcourir les fichiers locaux".
Ensuite vous ouvrez le dossier "localisation", et tous les fichiers sont là, avec les même noms (sauf les fichier du mod commençants par ww1), dans toutes les langues. Là, le mieux est de comparer les fichiers en anglais du jeu et ceux de wolferos pour voir les lignes en communs et les différences. Pour la version française on copie alors les lignes (du fichier français du jeu vers celui que vous créez) qui étaient les mêmes dans le mod et dans le jeu, et on traduit les autres.

Cela ne marche donc pas avec les fichiers commençants par ww1.

Par contre je suis désolé polemarque, mais j'ai proposé hier soir le fichier "equipment", les modifications apportées par wolferos s'élevants à peine à quelques lignes, avec le fichier français du jeu, ce fut rapide. Par contre je n'ai pas touché à ww1_events_I_french.

**Comment by Polemarque** [comment]
Ah, flûte. Tant pis, l'important c'est que ça soit fait, et de toutes façons j'ai plus avancé sur l'autre que sur equipments. Je vais donc finir "events"; si ça s'avère trop long -le fichier est vraiment énorme et les textes sont souvent des pavés-, je le proposerai peut-être en traduction partielle en vue de le finir en deux temps.

**Comment by Mindeufair** [comment]
Je te souhaite bien du plaisir ! Si tu veux je peux t'aider, tu me dis qu'elles lignes faire.

**Comment by Polemarque** [comment]
C'est gentil mais j'ai déjà pas mal avancé dans le désordre; beaucoup de ligne sont déjà traduites. Mais tiens-moi au courant si tu entame un autre des gros fichiers qui restent.

**Comment by Mindeufair** [comment]
Le truc, c'est qu'en se servant des traductions du jeu de base, les fichiers ne commençant pas par ww1 sont assez rapides à traduire, les modifications apportées par wolferos se limitant à une vingtaine de lignes tout au plus, je les fini donc rapidement, je te préviendrai donc seulement pour ceux créés par wolferos, les fichiers commençants par ww1.

**Comment by Ezorh** [comment]
Si vous avez besoin d'aide cela m'intéresse de traduire quelques uns des événements historiques qui surviennent. Par exemple le naufrage du Titanic. Mais j'ignore si cela fait partie du gros fichier sur lequel travail Polemarque déjà. Je ne suis pas très doué en code, je ne sais pas où on trouve ces textes. J'attends vos conseils et/ou votre feu vert/rouge.

**Comment by Mindeufair** [comment]
Ne t'inquiète pas ce n'est pas très compliqué de traduire des fichiers ^^
Ils se trouvent dans l'onglet "code", puis tu vas dans : 
mod/thegreatwar/localisation/

Là, tu as tout les textes que tu vois dans le jeu (ceux du mod), dans toutes les langues. Les fichiers commençants par ww1 n'existent pas du tout dans le jeu de base, les autres ont été modifiés par wolferos. Comme je l'ai dit plus haut, les modifications apportées aux fichiers du jeu de base restent peu nombreuses et ils sont donc rapide à traduire pour qui sais les retrouver (j'ai expliqué comment faire).

Dans ce fichier localisation, tu as plusieurs fichiers, qui donnent chacun les textes de différentes catégories, il existe un fichier par langue. Notre objectif et que tous ces fichier existent en français et qu'il soient intégralement traduit.
La langue du fichier est le dernier truc écrit avant ".yml", donc soit "english", "french", etc...

Aujourd'hui, quand tu vas dans le dossier, tu as plusieurs possibilités : soit tu trouves le fichier traduit en français, soit le fichier en français existe mais n'est pas traduit (ce qui permet d'avoir quand même un texte en anglais même s'il n'est pas traduit en jeu), soit le fichier n'existe pas du tout.

Dans le premier cas, il n'y a rien à faire, sauf si tu trouves une faute, que tu peux corriger, ou si tu trouves des passages qui ne sont pas traduits.
Dans le second cas, il il faut traduire les passages en anglais entre guillemets, mais attention, seulement ceux entre guillemets (sinon tu casses tout ^^).
Dans le dernier cas, il faut copier le fichier anglais puis remplacer les textes en anglais par des textes en français dans un nouveau fichier. Encore une fois, il faut que les textes soient entre guillemets. Il faut remplacer le "l_english" de la première ligne par "l_french", pour que le jeu comprenne que c'est en français. Une fois le fichier traduit et "l_english" remplacé par "l_french", il ne te restes plus qu'à mettre un nom au fichier, tu prendras donc celui du fichier anglais que tu as copié, et tu remplacera english par french.

Une fois tout cela fait, tu iras tout en bas de la page et tu cliquera sur le bouton propose new file ou si tu modifies un fichier, tu cliquera sur propose file change, puis dans la nouvelle page qui apparaît, tu cliques sur create pull request.

Voilà c'était long, mais je voulais que ce soit le plus clair possible, si tu ne comprends pas quelque chose, dis-le moi.

**Comment by Ezorh** [comment]
Merci d'avoir pris le temps d'être aussi précis. Je vais voir ce que je peux faire :-) Et ton message sera toujours utile aux nouveaux venus par la suite !

**Comment by Polemarque** [comment]
Oui Ezorh, l'évènement du naufrage du Titanic fait partie du gros fichier sur lequel je travaille; je l'ai déjà traduit. Mais tu peux prendre un nouveau fichier _ww1 non traduit pour bosser dessus; ou sinon les fichiers qui sont déjà traduits peuvent avoir besoin d'une relecture, il arrive que la première version de la traduction contienne des erreurs, des fautes d'orthographes ou des tournures de phrases maladroites, ça a besoin d'être corrigé aussi.

**Comment by Polemarque** [comment]
Il y a de gros problèmes de traduction et d'affichage depuis la mise à jour.
Les événements surviennent, mais leur titre ni leur texte ne s'affiche, il n'y a que la ligne de code qui leur est attribuée.
Certains arbres de priorités s'affichent correctement mais certains autres ont perdu la VF pour la période 39-45: les priorités de la période 14-18 sont traduites, mais celles de la seconde guerre mondiale sont revenues en anglais alors qu'elles étaient déjà traduites à la base.
Les noms des avions et des dirigeables ne s'affichent pas et leur description non plus, pour l'intégralité des arbres, pas seulement ceux de la premiére guerre mondiale.
Les arbres de recherche de l'artillerie sont correctement traduits, mais pour les matériels de la seconde guerre mondiale, ils sont tous remplacés par les icônes et les descriptions de l'arbre de recherche "standard" des pays mineurs.
Enfin, le même problème existe pour l'arbre de recherche naval: les navires de la période 1914-1934 n'ont aucun nom propre, seulement "croiseur I", "croiseur II", etc; ceux de la période 1934-1945 n'ont qu'une ligne de code en anglais comme nom. 

Comment peut-on réparer ça?

**Comment by Wolferos** [comment]
Certains problèmes d'affichages ont été réglés.
Il ne faut pas oublier d'encoder les fichiers en **UTF8 with BOM** sinon le moteur du jeu n'arrive pas toujours à rendre les textes.

**Comment by Polemarque** [comment]
Aïe aïe aïe, ça doit venir de là alors. Je ne savais pas qu'il fallait faire ça, du coup en ce qui me concerne je n'ai jamais encodé les fichiers que j'ai traduits... est-ce qu'on peut réencoder ces fichiers ici, où est-ce qu'il faut repasser au crible chaque fichier en l'encodant sur un logiciel de traitement de texte avant de le remettre ici?

**Comment by Wolferos** [comment]
Nous utilisons [Sublime Text ](https://www.sublimetext.com/), un outil rapide, léger et très puissant pour éditer des fichiers.
Dedans, il y a l'option de sauvegarder un fichier avec le bon encodage.
Nous avons ré-encoder tous les fichiers où c'était nécessaire.

Normalement, quand tu lances le jeu en mod Debug (avec l'option -debug), un fichier log apparaît avec toutes les erreurs de lancement. C'est là où l'on peut voir les éventuels problèmes d'encodage.

**Comment by bherbo** [comment]
bonsoir j'ai commencé à traduire en français certain fichier du jeu (bookmark notamment). Comment puis faire pour le partager?

**Comment by NicolasGrosjean** [comment]
Bonsoir, pour partager des fichiers, il faut que tu utilises [GitHub ](https://guides.github.com/)et plus particulièrement les [pull request](https://guides.github.com/activities/forking/).

**Comment by Polemarque** [comment]
La plupart des gros fichiers sont traduits maintenant?

**Comment by NicolasGrosjean** [comment]
> La plupart des gros fichiers sont traduits maintenant?

Il en reste encore quelque uns. Le plus gros encore à traduire semble être ww1_focus.

> Bonjour à tous, je tiens à préciser que nombreux sont les fichiers à traduire déjà présents dans le jeu de base, je conseil donc d'effectuer un copié-collé de ces traductions bien réalisée, cela évite une perte de temps inutile. Il faut juste être attentif au fait que Wolferos n'ai rien ajouté, il faudrait dans ce cas traduire ce qui n'est pas présent en vanilla dans le fichier

@Wolferos Ne serait-il pas plus judicieux de rassembler les modifications de localisation du jeu de base dans un seul fichier?
Dans l'état actuel, à chaque modification de Paradox, vous devez la merger alors que celle-ci n'impacte presque pas le mod.
Au niveau des traductions c'est encore pire car on doit merger ce qui est fait par les traducteurs de Paradox sans retraduire ce qui est fait par Paradox, tout en traduisant vos ajouts qui sont mélés à ceux de Paradox.
Rassembler la localisation surchargée dans un fichier est quelque chose qu'on fait souvent sur les mods de Ck2 mais ce n'a pas trop l'air d'être le cas sur HoI4 puisque Kaiserreich et BlackICE ne le font pas.

**Comment by NicolasGrosjean** [comment]
@Wolferos Un texte de l'écran d'accueil n'est pas traduisible car il est écrit directement dans une image.
![image](https://user-images.githubusercontent.com/13560473/34793306-2c175dc0-f64b-11e7-9963-909a0fe794aa.png)
Fichier : mod/thegreatwar/gfx/loadingscreens/load_tfv.dds

Serait-il possible de mettre le texte sous la même forme que l'autre message de cette page afin qu'il soit traduisible ?

**Comment by Polemarque** [comment]
Est-ce que quelqu'un travaille déjà sur le fichier  ww1_focus ?

**Comment by NicolasGrosjean** [comment]
@Polemarque Je ne suis pas dessus et je veux bien te le laisser.
Par ailleurs, j'ai vu que tu étais un habitué de Mundus, [ceci devrait t'aider si tu ne l'as pas déjà vu](https://www.mundusbellicus.fr/forum/espace-communautaire/p%C3%B4le-de-traduction/556532-outil-paradox-translate-helper).

**Comment by Polemarque** [comment]
Entendu, je vais m'y attaquer alors. Si quelqu'un d'autre l'a déjà entamé qu'il se manifeste, que nos efforts ne soient pas gaspillés inutilement! Parce que le fichier est extrêmement long.
