### ISSUE TITLE
Incorrect file encoding

### ISSUE THREAD

**Issue by Proho16** [Wolferos/Hearts-of-Iron-IV-The-Great-War#374]
The file ww1_aircraft_ww2_l_german.yml unfortunately has the wrong coding. UTF-BOM instead of UTF-BOM-8.

**Comment by Proho16** [comment]
Bug

**Comment by Wolferos** [comment]
What Editing software do you use?

**Comment by Proho16** [comment]
I use Notpad++
Since I don't have permission to upload, I can't change the coding. My predecessor has already uploaded it incorrectly. It would have to be re-uploaded by someone with permission, with the correct encoding.

**Comment by Proho16** [comment]
Error sat in front of the computer.
I finish.
