### ISSUE TITLE
Abdication of Tsar Nicholas II

### ISSUE THREAD

**Issue by Ezekil** [Wolferos/Hearts-of-Iron-IV-The-Great-War#42]
Good day to you, sir! 
Wanted to point that chain of event for October revolution is kinda dope. It seems that time trigger for it was shifted to 1914 (1915) instead of 1917, so the revolution starts way earlier....
https://pp.vk.me/c636630/v636630481/49bc4/fEBPIyd19rY.jpg
https://pp.vk.me/c636630/v636630481/49bce/ITZEPPaurQM.jpg

**Comment by Wolferos** [comment]
Hello Ezekil

The October Revolution is set to trigger if the Russian Empire takes too many defeats and looses too many lands too. It doesn't trigger with a date because for each game, the situation can be very different.
