### ISSUE TITLE
Cannot research

### ISSUE THREAD

**Issue by xakod** [Wolferos/Hearts-of-Iron-IV-The-Great-War#521]
Hello, first of all, thanks for this mod. But secondly, I've issue.
I cannot research anything by any country 
![screen](https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/assets/26579016/44a4f1b6-388c-4013-adc5-1cafc0cdf087)
Looks like dog (?) blocks it.

**Comment by Reshariti** [comment]
Have you figured out how to solve this problem?

**Comment by xakod** [comment]
> Have you figured out how to solve this problem?
> 

I have problem with my hoi4 installation, it wasn't mod problem. Maybe you had the same.
