### ISSUE TITLE
Polish Translation

### ISSUE THREAD

**Issue by BaCe21** [Wolferos/Hearts-of-Iron-IV-The-Great-War#60]
Is there any possibilty of adding polish translation? I can help of course

**Comment by DevilIris** [comment]
Sure, Edit the .YML Files in the localisation folder of the mod

**Comment by BaCe21** [comment]
but only something like copy the autonomy_l_english.yml, then change the name to autonomy_l_polish.yml and start changing?

Edit: If yes, I'm starting doing it right now. PS. I can't find the diplomacy_l_english.yml file

**Comment by DevilIris** [comment]
Yes, you need to translate all, You can take other modes of translation for example like Japan translation or the italian then translate the mod

**Comment by BaCe21** [comment]
Okay, understood. But still, I have 2 issues:
1. The diplomacy file, still can't find the english version (I am not very good in german)
2. If I complete a file, how can I send, or show it?

**Comment by DevilIris** [comment]
1.- you can upload to mediafire or dropbox and publish here 

2.- The diplomacy in english is in the base game

**Comment by BaCe21** [comment]
sounds good, i've already translated factions_l_english file to polish, do you want to see this "sample"? To see am I doing it in the right way?

**Comment by Wolferos** [comment]
Hey @BaCe21 

You can see a short tutorial here https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/issues/38#issuecomment-276652257 . Of course, you will have to change the value according to the polish ones (l_polish and *_l_polish.yml)

**Comment by BaCe21** [comment]
okay, now i fully understand (i hope so), so if I finish a part of translation, should I share it somewhere? (of course sorry for my english sometimes, I'm only a common Polish)

**Comment by Wolferos** [comment]
You can send a Pull Request (https://help.github.com/articles/creating-a-pull-request/) et we will merge your work into the Mod.

**Comment by BaCe21** [comment]
wait, I am new here(12 days exactly), what does it mean that i am "assigned"?

**Comment by BaCe21** [comment]
okay so, i've got some files (i've begun with these smaller ones) translated into polish. Now, how can i send it to you, Wolferos?

**Comment by Wolferos** [comment]
Sure. Make a Pull Request or if you can't upload it somewhere and we'll upload it for you.

**Comment by BaCe21** [comment]
So from now I take all responsibility for polish translation and my work will be added directly into the mod?

**Comment by BaCe21** [comment]
so when will the first part of my files added to mod as "early" localization?
