### ISSUE TITLE
Meta: The Github isn't letting me upload junk

### ISSUE THREAD

**Issue by Anony1200** [Wolferos/Hearts-of-Iron-IV-The-Great-War#61]
I was gonna just wait 'til you washed up on Steam or whatnot to mention this, but you're DEAD again so I'll say this here.

Had the Localisation file complete for a bit. Here's an expirebox with all the junk in in case one of you boys is able to magically get it to upload: https://expirebox.com/download/defa2b8687709633c70e0ebe08109e9f.html

Otherwise, it's simply not letting me put up the files, despite the fact that I should logically be able to. Anyway, next up is the weapon model names and weapon tech descriptions.

**Comment by Wolferos** [comment]
Like seen on Steam, your commit has been pushed here https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/commit/a882132a7f98bd68b67a61881c34b25e2f9cc3e2
