### ISSUE TITLE
Suggestions and some problems

### ISSUE THREAD

**Issue by LlewellynX** [Wolferos/Hearts-of-Iron-IV-The-Great-War#81]
Hi, 

I noticed a few things during gameplay. Not sure if these qualify as issues, but this is my first time on GitHub and I couldn't find anywhere else to post.

- Couldn't stage a coup in another country as Germany. Seems that Authoritarian governments can't do this in other Authoritarian countries. During the War, one strategy that Germany employed against Russia was agitating their various minorities. Near the end of the war some of this paid off. Both Poland and the Ukraine where going to be puppet monarchies if Germany won the war. (There was also talk of Austria-Hungary becoming a Tri-Monarchy with poland. Finland actually had a German Prince crowned as king. Glacia was to become part of Austria-Hungary. Germany wanted to annex Belgium and the French territory directly to the West of Belgium and lots of other good things.)

- Playing Germany I managed to force Russia out (with some help from the soviets), and Belgium, Holland, and France all "capitulated", but this didn't end the war with any of these countries. It just kept going. As it is it is very difficult if not impossible to win.

- England was not part of the Entente. They joined for their own reasons, mostly they were scared of Germany, but they never had any treaty obligations to fight. Germany's invasion of Belgium was the excuse given, but even this invasion did not require them to join the war. It would be nice if their was a way to make England's participation not be a sure thing. Germany at the time didn't think they would get involved.

-  Of course everyone knows the assassination was the start of the war, but what if the assassination failed? It would be cool to see that option incorporated. Franz Ferdinand was a pacifist and he prevented the Great War happening in 1910, 1911, 1912, and 1913. 

- England bribed the Italians with 200 million pounds of gold to come in on the side of the Entente. If Russia had attacked Austria-Hungary before Germany declared war, Italy's treat with the central powers would have brought them in on the Central Power's side.

- Currently there is no way to become involved in any of the events. Players cannot interfere in any of the Rebellions or wars that happen up until the big one. It would be nice if their could be more interaction with history.

- Austria-Hungary's biggest threat was Germany. They fought a war shortly after Germany unified and Germany still had its eye on Austria-Hungary by 1914. I'd love to be able to see Germany attack Austria, but currently there is no way to do this.

- Once the war starts all the players come in the same way they did in reality. It doesn't matter how much Political Power you use to sway a country from not joining against you, they will always follow the same path. This makes some of the features of the game irrelevant.

- If Franz Ferdinade survived the assassination he was going to transform the empire into the United States of Austria Hungary. Even had a map commissioned. 

- Germany started suing for peace almost immediately after the failure of their invasion of France, but they sought a separate peace with Russia. At the start of the war England, France and Russia agreed not to sign a separate peace. It would be fun to have an option where one of the major powers does sue for a separate peace. A policy tree choice might work well

- Italy would have joined on the Central Powers side even though neither Germany or Austria had been attacked, but only if Austria ceded land on their border with Italy where the population was ethnically and linguistically Italian and all but handed over Albania. Another cool option choice.

- The Russian Revolution happened because Germany helped the communist leaders enter into Russian after the provisional government chose to remain in the war (although an option here to sue for peace would be neat). Their should be a policy choice for Germany or Austria to aid the communists, otherwise the October Revolution would not have happened.

- Too much of the game relies on a high world tension, like invite someone to your faction. Even if they love you 100%, you still cannot invite them in.

Hope you find this useful, its what I noticed playing the mod.

**Comment by Wolferos** [comment]
Hello @LlewellynX 

Thanks for your feedbacks and suggestions

> Couldn't stage a coup in another country as Germany. Seems that Authoritarian governments can't do this in other Authoritarian countries. During the War, one strategy that Germany employed against Russia was agitating their various minorities. Near the end of the war some of this paid off. Both Poland and the Ukraine where going to be puppet monarchies if Germany won the war. (There was also talk of Austria-Hungary becoming a Tri-Monarchy with poland. Finland actually had a German Prince crowned as king. Glacia was to become part of Austria-Hungary. Germany wanted to annex Belgium and the French territory directly to the West of Belgium and lots of other good things.)

It something that would be interesting to do but we can't really implement in game due to the base game mechanics. It would require tons of modifiers and events for little effects in the end.


> Playing Germany I managed to force Russia out (with some help from the soviets), and Belgium, Holland, and France all "capitulated", but this didn't end the war with any of these countries. It just kept going. As it is it is very difficult if not impossible to win.

We still need to implement the Treaty of Berlin but depending on the world's situation, it's hard to make a script that would please players. Maybe an event with a scripted Peace with the choice to choose it or let the Peace Conference happens.


> England was not part of the Entente. They joined for their own reasons, mostly they were scared of Germany, but they never had any treaty obligations to fight. Germany's invasion of Belgium was the excuse given, but even this invasion did not require them to join the war. It would be nice if their was a way to make England's participation not be a sure thing. Germany at the time didn't think they would get involved.

England is no longer part of the Entente and is free to join it or not. You can also join the Central Powers if you'd like.


> Of course everyone knows the assassination was the start of the war, but what if the assassination failed? It would be cool to see that option incorporated. Franz Ferdinand was a pacifist and he prevented the Great War happening in 1910, 1911, 1912, and 1913.

It's true. Maybe a small chance for the assassination to fail but what plan after ? The reactions, etc.


> England bribed the Italians with 200 million pounds of gold to come in on the side of the Entente. If Russia had attacked Austria-Hungary before Germany declared war, Italy's treat with the central powers would have brought them in on the Central Power's side.
> Italy would have joined on the Central Powers side even though neither Germany or Austria had been attacked, but only if Austria ceded land on their border with Italy where the population was ethnically and linguistically Italian and all but handed over Albania. Another cool option choice.

Italy can either join the Entente or either join the Central Powers. Depending of the events, Italy will pick a side. For example, if Austria-Hungary gives lands to Italy, there is a great chance for Italy to remain in the Central Powers


> Currently there is no way to become involved in any of the events. Players cannot interfere in any of the Rebellions or wars that happen up until the big one. It would be nice if their could be more interaction with history.

It's because of the revolt mechanic and the things that could happen. For example, for a simple rebellion, a country could invite all their allies, Faction's members. Plus the AI has difficulties to properly annex a revolt after that. We've had the case with the Russian Civil War.


> Austria-Hungary's biggest threat was Germany. They fought a war shortly after Germany unified and Germany still had its eye on Austria-Hungary by 1914. I'd love to be able to see Germany attack Austria, but currently there is no way to do this.

Leaving the Central Powers can give you this opportunity.


> Once the war starts all the players come in the same way they did in reality. It doesn't matter how much Political Power you use to sway a country from not joining against you, they will always follow the same path. This makes some of the features of the game irrelevant.

Nation Focuses, events can change that but when the World Tension reaches a certain amount, we can't really control the game anymore.


> Germany started suing for peace almost immediately after the failure of their invasion of France, but they sought a separate peace with Russia. At the start of the war England, France and Russia agreed not to sign a separate peace. It would be fun to have an option where one of the major powers does sue for a separate peace. A policy tree choice might work well

It's a good idea but the Peace Conference doesn't give us much option about that. Plus we would have to make separate wars that would be merged automaticaly by the Game


> The Russian Revolution happened because Germany helped the communist leaders enter into Russian after the provisional government chose to remain in the war (although an option here to sue for peace would be neat). Their should be a policy choice for Germany or Austria to aid the communists, otherwise the October Revolution would not have happened.

It's hard to combinate events like those with a Revolution, too many factors in the balance


> Too much of the game relies on a high world tension, like invite someone to your faction. Even if they love you 100%, you still cannot invite them in.

It's a thing that need to be reworked but the WT is a sensible matters because most of the player's actions can change what we originally planned.

It's always about making a choice between what we want, what we could  do and what the game let us do.
