### ISSUE TITLE
arabic support

### ISSUE THREAD

**Issue by OmarAglan** [Wolferos/Hearts-of-Iron-IV-The-Great-War#90]
hello 
my name is omar
a transletor
how can i add arabic

**Comment by Darmabfall88** [comment]
By the Game Files in Hoi4 The Great War copy all from English and make all Arabic

**Comment by Wolferos** [comment]
As Arabic Language is not officialy supported by Paradox (like Chinese, Japanese and Turkish), you'll have to make your own SubMod on the Workshop that will only replace the English Localisation files.

For Localisation SubMod Example: 
- http://steamcommunity.com/sharedfiles/filedetails/?id=803029506
- http://steamcommunity.com/sharedfiles/filedetails/?id=854550667

You'll find all the information needed to create a SubMod here http://www.hoi4wiki.com/Modding

Thanks for your help Omar

**Comment by Omaranwa** [comment]
OK I Will work in it
